[package]
name = "hello_triangles"
version = "0.1.0"
edition = "2024"

[dependencies]
shame_wgpu = { path = "../../shame_wgpu" }
shame = { path = "../../shame" }
wgpu = {workspace = true}
bytemuck = { version = "1.25.2", features = ["derive"] }
glam = { version = "0.33.3", features = ["bytemuck", "cuda"] } # "cuda" for 8-byte aligned Vec2
winit = "0.30.13"
pollster = "1.0.1"
thiserror = "2.0.20"
